### ISSUE TITLE
Ongoing buffy issues

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/test-pyos-review#7]
- [ ] Assign editor doesn't include message element 

why doesn't it include the custom message provided in the yaml - it does however return a template - why? the eic command should provide that template but not the editor command

```yaml
    assign_editor:
      only: editors
      add_as_assignee: true
      message: "Hey :wave: ! Let's get this review going. The editor guide can be found at https://www.pyopensci.org/software-peer-review/how-to/editors-guide.html"
      add_labels:
        - "1/editor-assigned"
      remove_labels:
        - "0/pre-review-checks"
        - "New Submission!"
```
<img width="1011" alt="Screenshot 2024-03-14 at 11 25 07 AM" src="https://github.com/pyOpenSci/test-pyos-review/assets/7649194/94c0b89d-655f-4edb-9274-1868a718d562">
